; Script generated by the Inno Setup compiler

[Setup]
AppName=Android Bootloader Flasher
AppVersion=1.0.0
DefaultDirName={commonpf64}\AndroidBootloaderFlasher
DefaultGroupName=Android Bootloader Flasher
OutputBaseFilename=AndroidBootloaderFlasherSetup
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin
OutputDir=..\dist

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "..\AndroidBootloaderFlasher.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\README.md"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\Android Bootloader Flasher"; Filename: "{app}\AndroidBootloaderFlasher.ps1"; WorkingDir: "{app}"
Name: "{commondesktop}\Android Bootloader Flasher"; Filename: "{app}\AndroidBootloaderFlasher.ps1"; WorkingDir: "{app}"

[Run]
Filename: "powershell.exe"; Parameters: "-ExecutionPolicy Bypass -File ""{app}\AndroidBootloaderFlasher.ps1"""; WorkingDir: "{app}"; Flags: runhidden
